sudo: false

branches:
  only:
    - master

language: java
jdk:
  - openjdk8

script:
  - mvn clean package

notifications:
  email:
    recipients:
      - sergey@shimkiv.com
    on_failure: always
